% Matthew J. Begneaud, 10/12/15
% Run SCCA design code
% apply the scale factors h, omega, and beta
%
% This is a RDFDFDFD cam
% The rate of rotation is 4 RPM

clear
clc


% %%%%%%%%%%%%%% Constants %%%%%%%%%%%%%%%%%%%%%%

N=100;
omega=2*pi*4/60; 

h1=2.5; %units are inches
betarise=40*pi/180;
highdwell=100*pi/180;

h2=1.5; %units are inches
fall1=90*pi/180;
dwell1=20*pi/180;

h3=0.5; %units are inches
fall2=30*pi/180;
dwell2=40*pi/180;

h4=0.5; %units are inches
fall3=30*pi/180;
dwell3=2*pi-(betarise+highdwell+fall1+dwell1+fall2+dwell2+fall3);




% %%%%%%%%%%%%%%%%%%%% SCCA call and Y value reassignments %%%%%%%%%%%%%%%%
% All rises and falls are solved for as rises using scca and then all are 
% reassigned as correct-intensity rise or falls below the scca function calls

[xrise yrise yprise ydblprise ytrplprise]=scca('modified trapezoid','rise');

xrise1=xrise;
yrise1=h1*yrise;
yprise1=h1*yprise;
ydblprise1=h1*ydblprise;
ytrplprise1=h1*ytrplprise;

xfall1=xrise;
yfall1=h1-h2*yrise;
ypfall1=-h2*yprise;
ydblpfall1=-h2*ydblprise;
ytrplpfall1=-h2*ytrplprise;

xfall2=xrise;
yfall2=(h1-h2)-h3*yrise;
ypfall2=-h3*yprise;
ydblpfall2=-h3*ydblprise;
ytrplpfall2=-h3*ytrplprise;

xfall3=xrise;
yfall3=h3-h4*yrise;
ypfall3=-h4*yprise;
ydblpfall3=-h4*ydblprise;
ytrplpfall3=-h4*ytrplprise;




% %%%%%%%%%%%%%%%%% Y values for dwells %%%%%%%%%%%%%%%%%%%%%%%%%%%

yhighdwell=h1*ones(1,N);
yphighdwell=zeros(1,N);
ydblphighdwell=zeros(1,N);
ytrplphighdwell=zeros(1,N);

ydwell1=(h1-h2)*ones(1,N);
ypdwell1=zeros(1,N);
ydblpdwell1=zeros(1,N);
ytrplpdwell1=zeros(1,N);

ydwell2=h3*ones(1,N);
ypdwell2=zeros(1,N);
ydblpdwell2=zeros(1,N);
ytrplpdwell2=zeros(1,N);

ydwell3=zeros(1,N);
ypdwell3=zeros(1,N);
ydblpdwell3=zeros(1,N);
ytrplpdwell3=zeros(1,N);




% %%%%%%%%%%%%%%%%%%% Theta Values %%%%%%%%%%%%%%%%%%%%%%%%%%%%

thetarise=xrise1*betarise;
thetahighdwell=betarise+[1:N]*highdwell/N;
thetafall1=max(thetahighdwell)+xfall1*fall1;
thetadwell1=max(thetafall1)+[1:N]*dwell1/N;
thetafall2=max(thetadwell1)+xfall2*fall2;
thetadwell2=max(thetafall2)+[1:N]*dwell2/N;
thetafall3=max(thetadwell2)+xfall3*fall3;
thetadwell3=max(thetafall3)+[1:N]*dwell3/N;




% %%%%%%%%%%%%%%%%%%%%%% Generated Vectors %%%%%%%%%%%%%%%%%%%%%%%%%
% Below, the entire 360 degree set of theta, S, V, A, and J values are
% assembled into vectors

theta=[thetarise thetahighdwell thetafall1 thetadwell1 thetafall2 thetadwell2 thetafall3 thetadwell3];
S=[yrise1 yhighdwell yfall1 ydwell1 yfall2 ydwell2 yfall3 ydwell3];
V=omega*[yprise/betarise yphighdwell ypfall1/fall1 ypdwell1 ypfall2/fall2 ypdwell2 ypfall3/fall3 ypdwell3];
A=omega^2*[ydblprise/betarise^2 ydblphighdwell ydblpfall1/fall1^2 ydblpdwell1 ydblpfall2/fall2^2 ydblpdwell2 ydblpfall3/fall3^2 ydblpdwell3];
J=omega^3*[ytrplprise/betarise^3 ytrplphighdwell ytrplpfall1/fall1^3 ytrplpdwell1 ytrplpfall2/fall2^3 ytrplpdwell2 ytrplpfall3/fall3^3 ytrplpdwell3];




% %%%%%%%%%%%%%%%%%%% Plot Settings %%%%%%%%%%%%%%%%%%%%%%%%%
%Figure 1 is generated by the SCCA function and shows only the normalized
%lift, velocity, and acceleration during the rise segment for the selected
%SCCA function type

figure(2)
subplot(2,2,1)
plot(theta*180/pi,S)
axis tight
xlabel('Theta, deg')
ylabel('Displacement, in')
grid on
subplot(2,2,2)
plot(theta*180/pi,V)
axis tight
xlabel('Theta, deg')
ylabel('Velocity, in/s')
grid on
subplot(2,2,3)
plot(theta*180/pi,A)
xlabel('Theta, deg')
ylabel('Acceleration, in/s^2')
axis tight
grid on
subplot(2,2,4)
plot(theta*180/pi,J)
axis tight
xlabel('Theta, deg')
ylabel('Jerk, in/s^3')
grid on
maxS=max(S)
maxV=max(V) 
maxA=max(A) 
maxJ=max(J)

